### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by RisingStarPF2e** [scari08/pf2e-chance#1]
Hello, I was interested in testing this module out but when I try to install the 1.02 via either manifest, the forge bazaar or through the module install dialogue in-foundry I just get no installation sorta like a invalid .json. 

I tried installing the 1.01 and that definitively gives me a manifest error.

Not sure what the issue exactly is. But I'de love to try this out as I love the idea of showing players the percentages when they attempt to do something!

**Comment by scari08** [comment]
pushed 1.0.3 release that should fix this

**Comment by RisingStarPF2e** [comment]
Yup! This fixed it! :D Been messing with this and this is something I've always wanted. Player feedback without needing to explain every single strike all of the time / discovery of the math. Big fan!
